# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-24 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock_change',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('p_change', models.CharField(max_length=100)),
                ('price_change', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('code',),
            },
        ),
    ]
