# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-24 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_stock_change'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stock_change',
        ),
        migrations.AddField(
            model_name='stock',
            name='p_change',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='price_change',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
