# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-25 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_auto_20181224_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='gpr',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='npr',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='pe',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
